from cv2 import aruco

CHESSBOARD_PATTERN_SIZE = (11, 8)
CHESSBOARD_SQUARE_SIZE = 15
CHESSBOARD_CORNER_WINDOW_SIZE = (5, 5)

ARUCO_DICT_TYPE = aruco.DICT_6X6_1000
ARUCO_MARKER_LENGTH = 80
ARUCO_CORNER_WINDOW_SIZE = (5, 5)
ARUCO_CALIB_FULL_MIN_NUM = 5
ARUCO_CALIB_HALF_MIN_NUM = 3

HANDEYE_MARKER_TYPE = 'chessboard'
